apiVersion: v1
kind: Pod
metadata:
  name:   privileged
spec:
  containers:
    - name:  alpine
      image: alpine:latest
      args: [sh, -c, 'while true; do sleep 100000; done']
      securityContext:
        privileged: true
      volumeMounts:
        - name: sys
          mountPath: /sys
  volumes:
    - name: sys
      hostPath:
        path: /sys
