apiVersion: v1
kind: Pod
metadata:
  name:   busybox
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
spec:
  containers:
    - name:    busybox
      image: busybox:latest
      args: [sh, -c, 'while true; do echo "hello there!"; sleep 10; done']
