apiVersion: v1
kind: Pod
metadata:
  name:   debian-nocap
spec:
  containers:
    - name:    debian
      image: debian:stretch
      args: [sh, -c, 'echo $UID && sleep 600']
      securityContext:
        capabilities:
          drop:
            - CHOWN
            - DAC_OVERRIDE
            - FSETID
            - FOWNER
            - MKNOD
            - NET_RAW
            - SETGID
            - SETUID
            - SETFCAP
            - SETPCAP
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - KILL
            - AUDIT_WRITE
