apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: no-egress
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
