apiVersion: v1
kind: ReplicationController
metadata:
  name:   pause
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
        - name:    pause
          image: gcr.io/google_containers/pause
