apiVersion: v1
kind: Pod
metadata:
  name:   busybox2
spec:
  initContainers:
    - name:    init
      image: busybox:latest
      args: [sh, -c, 'ln -s /etc /foo/etc']
      volumeMounts:
        - name: base
          mountPath: /foo
  containers:
    - name:    busybox
      image: busybox:latest
      args: [sh, -c, 'if [[ -d /etc/bar ]]; then exit 1; else sleep 1000000; fi']
      volumeMounts:
        - name: base
          mountPath: /foo
        - name: nested
          mountPath: /foo/etc/bar
    - name:    observer
      image: busybox:latest
      args: [sh, -c, 'while true; do sleep 1000; done']
      volumeMounts:
        - name: nested
          mountPath: /bar
  volumes:
    - name: base
      emptyDir: {}
    - name: nested
      emptyDir: {}
