apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-hello
  labels:
    app: http-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-hello
  template:
    metadata:
      labels:
        app: http-hello
    spec:
      containers:
      - name: http-hello
        image: gcr.io/stclair-gcr-pub/http-hello:{{TAG}}
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: http-hello
spec:
  selector:
    app: http-hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
